version: '3.2'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - $HOME/dockerdata/private_chat/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=private_chat
      - MYSQL_ROOT_HOST=%
    networks:
      - privatechat

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - $HOME/dockerdata/private_chat/upload:/app/upload
      - $HOME/dockerdata/private_chat/logs:/app/logs
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=private_chat
      - JWT_AUTH_SECRET=abc123456 # jwt的secret
    networks:
      - privatechat
    depends_on:
      - db
    # https://docs.docker.com/compose/startup-order/
    # depends on只会等待服务启动，不会等到db等初始化完成，所以只用depends on后连接数据库会报错
    command: [ "./wait-for-it.sh", "db:3306", "--", "pm2-runtime", "/app/src/server.js" ]

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - 28080:80
    networks:
      - privatechat
    depends_on:
      - server
    
networks:
    privatechat:
      external: false